# Desativa o servidor web (HTTP) automático do Spring para não conflitar com nosso Motor TCP na 8080
spring.main.web-application-type=reactive
# Garante que os logs da nossa aplicação apareçam no console
logging.level.com.argus=INFO
# Formata o log para ficar mais legível
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n

# Shard 01 (Postgres na porta 5433 do Docker)
spring.r2dbc.shard1.url=r2dbc:postgresql://localhost:5433/argus_shard_01
spring.r2dbc.shard1.username=nome
spring.r2dbc.shard1.password=senha

# Shard 02 (Postgres na porta 5434 do Docker)
spring.r2dbc.shard2.url=r2dbc:postgresql://localhost:5434/argus_shard_02
spring.r2dbc.shard2.username=nome
spring.r2dbc.shard2.password=senha

server.port=8081